# Generated by Django 6.0.4 on 2026-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='opening_hours',
            field=models.CharField(max_length=100),
        ),
    ]
