# Generated by Django 6.1.1 on 2026-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOfMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingridients', models.TextField()),
                ('weight', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
