# Generated by Django 6.0.4 on 2026-09-19 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_APP', '0002_cartofmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='media/restorant_photos/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('opening_hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cartofmenu',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='media/dish_photos/'),
        ),
        migrations.AddField(
            model_name='cartofmenu',
            name='time_to_cook',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_APP.cartofmenu'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('cooking', 'Готується'), ('on_way', 'В дорозі'), ('delivered', 'Доставлено')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartofmenu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cartofmenu',
            name='weight',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='cartofmenu',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='delivery_APP.restorantinfo'),
        ),
    ]
