# Generated by Django 6.0.4 on 2026-10-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_APP', '0003_restorantinfo_cartofmenu_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва ресторану')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Контактна особа')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('opening_hours', models.CharField(max_length=100, verbose_name='Години роботи')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
